/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tp.bigdata.batchlayer.schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ProductPropertyValue extends org.apache.thrift.TUnion<ProductPropertyValue, ProductPropertyValue._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProductPropertyValue");
  private static final org.apache.thrift.protocol.TField BARCODE_FIELD_DESC = new org.apache.thrift.protocol.TField("barcode", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("description", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField STOCK_FIELD_DESC = new org.apache.thrift.protocol.TField("stock", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField SALE_PRICE_FIELD_DESC = new org.apache.thrift.protocol.TField("salePrice", org.apache.thrift.protocol.TType.DOUBLE, (short)4);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BARCODE((short)1, "barcode"),
    DESCRIPTION((short)2, "description"),
    STOCK((short)3, "stock"),
    SALE_PRICE((short)4, "salePrice");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BARCODE
          return BARCODE;
        case 2: // DESCRIPTION
          return DESCRIPTION;
        case 3: // STOCK
          return STOCK;
        case 4: // SALE_PRICE
          return SALE_PRICE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BARCODE, new org.apache.thrift.meta_data.FieldMetaData("barcode", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("description", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STOCK, new org.apache.thrift.meta_data.FieldMetaData("stock", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.SALE_PRICE, new org.apache.thrift.meta_data.FieldMetaData("salePrice", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProductPropertyValue.class, metaDataMap);
  }

  public ProductPropertyValue() {
    super();
  }

  public ProductPropertyValue(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public ProductPropertyValue(ProductPropertyValue other) {
    super(other);
  }
  public ProductPropertyValue deepCopy() {
    return new ProductPropertyValue(this);
  }

  public static ProductPropertyValue barcode(java.lang.String value) {
    ProductPropertyValue x = new ProductPropertyValue();
    x.setBarcode(value);
    return x;
  }

  public static ProductPropertyValue description(java.lang.String value) {
    ProductPropertyValue x = new ProductPropertyValue();
    x.setDescription(value);
    return x;
  }

  public static ProductPropertyValue stock(double value) {
    ProductPropertyValue x = new ProductPropertyValue();
    x.setStock(value);
    return x;
  }

  public static ProductPropertyValue salePrice(double value) {
    ProductPropertyValue x = new ProductPropertyValue();
    x.setSalePrice(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case BARCODE:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'barcode', but got " + value.getClass().getSimpleName());
      case DESCRIPTION:
        if (value instanceof java.lang.String) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.String for field 'description', but got " + value.getClass().getSimpleName());
      case STOCK:
        if (value instanceof java.lang.Double) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Double for field 'stock', but got " + value.getClass().getSimpleName());
      case SALE_PRICE:
        if (value instanceof java.lang.Double) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type java.lang.Double for field 'salePrice', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case BARCODE:
          if (field.type == BARCODE_FIELD_DESC.type) {
            java.lang.String barcode;
            barcode = iprot.readString();
            return barcode;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case DESCRIPTION:
          if (field.type == DESCRIPTION_FIELD_DESC.type) {
            java.lang.String description;
            description = iprot.readString();
            return description;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case STOCK:
          if (field.type == STOCK_FIELD_DESC.type) {
            java.lang.Double stock;
            stock = iprot.readDouble();
            return stock;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case SALE_PRICE:
          if (field.type == SALE_PRICE_FIELD_DESC.type) {
            java.lang.Double salePrice;
            salePrice = iprot.readDouble();
            return salePrice;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case BARCODE:
        java.lang.String barcode = (java.lang.String)value_;
        oprot.writeString(barcode);
        return;
      case DESCRIPTION:
        java.lang.String description = (java.lang.String)value_;
        oprot.writeString(description);
        return;
      case STOCK:
        java.lang.Double stock = (java.lang.Double)value_;
        oprot.writeDouble(stock);
        return;
      case SALE_PRICE:
        java.lang.Double salePrice = (java.lang.Double)value_;
        oprot.writeDouble(salePrice);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case BARCODE:
          java.lang.String barcode;
          barcode = iprot.readString();
          return barcode;
        case DESCRIPTION:
          java.lang.String description;
          description = iprot.readString();
          return description;
        case STOCK:
          java.lang.Double stock;
          stock = iprot.readDouble();
          return stock;
        case SALE_PRICE:
          java.lang.Double salePrice;
          salePrice = iprot.readDouble();
          return salePrice;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case BARCODE:
        java.lang.String barcode = (java.lang.String)value_;
        oprot.writeString(barcode);
        return;
      case DESCRIPTION:
        java.lang.String description = (java.lang.String)value_;
        oprot.writeString(description);
        return;
      case STOCK:
        java.lang.Double stock = (java.lang.Double)value_;
        oprot.writeDouble(stock);
        return;
      case SALE_PRICE:
        java.lang.Double salePrice = (java.lang.Double)value_;
        oprot.writeDouble(salePrice);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case BARCODE:
        return BARCODE_FIELD_DESC;
      case DESCRIPTION:
        return DESCRIPTION_FIELD_DESC;
      case STOCK:
        return STOCK_FIELD_DESC;
      case SALE_PRICE:
        return SALE_PRICE_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public java.lang.String getBarcode() {
    if (getSetField() == _Fields.BARCODE) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'barcode' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setBarcode(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.BARCODE;
    value_ = value;
  }

  public java.lang.String getDescription() {
    if (getSetField() == _Fields.DESCRIPTION) {
      return (java.lang.String)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'description' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setDescription(java.lang.String value) {
    if (value == null) throw new java.lang.NullPointerException();
    setField_ = _Fields.DESCRIPTION;
    value_ = value;
  }

  public double getStock() {
    if (getSetField() == _Fields.STOCK) {
      return (java.lang.Double)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'stock' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setStock(double value) {
    setField_ = _Fields.STOCK;
    value_ = value;
  }

  public double getSalePrice() {
    if (getSetField() == _Fields.SALE_PRICE) {
      return (java.lang.Double)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'salePrice' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setSalePrice(double value) {
    setField_ = _Fields.SALE_PRICE;
    value_ = value;
  }

  public boolean isSetBarcode() {
    return setField_ == _Fields.BARCODE;
  }


  public boolean isSetDescription() {
    return setField_ == _Fields.DESCRIPTION;
  }


  public boolean isSetStock() {
    return setField_ == _Fields.STOCK;
  }


  public boolean isSetSalePrice() {
    return setField_ == _Fields.SALE_PRICE;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof ProductPropertyValue) {
      return equals((ProductPropertyValue)other);
    } else {
      return false;
    }
  }

  public boolean equals(ProductPropertyValue other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  public int compareTo(ProductPropertyValue other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
